/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.doubleaaexpress.views;

import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author steve
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSignIn = new JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mSignUp = new JMenu();
        miRegisterAdministrator = new JMenuItem();
        miRegisterBuyer = new JMenuItem();
        miRegisterSeller = new JMenuItem();
        miRegisterCustomer = new JMenuItem();
        miRegisterMechanic = new JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main View");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main.jpg"))); // NOI18N

        bSignIn.setBackground(new java.awt.Color(0, 0, 153));
        bSignIn.setForeground(new java.awt.Color(255, 255, 255));
        bSignIn.setText("Sign In");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(bSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        mSignUp.setBackground(new java.awt.Color(0, 0, 153));
        mSignUp.setForeground(new java.awt.Color(0, 0, 0));
        mSignUp.setText("Sign Up");
        mSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        miRegisterAdministrator.setText("Register as Administrator");
        mSignUp.add(miRegisterAdministrator);

        miRegisterBuyer.setText("Register as Buyer");
        mSignUp.add(miRegisterBuyer);

        miRegisterSeller.setText("Register as Seller");
        mSignUp.add(miRegisterSeller);

        miRegisterCustomer.setText("Register as Customer");
        mSignUp.add(miRegisterCustomer);

        miRegisterMechanic.setText("Register as Mechanic");
        mSignUp.add(miRegisterMechanic);

        jMenuBar1.add(mSignUp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    public JButton getbSignIn() {
        return bSignIn;
    }

    public void setbSignIn(JButton bSignIn) {
        this.bSignIn = bSignIn;
    }
    
    public JMenu getmSignUp() {
        return mSignUp;
    }

    public void setmSignUp(JMenu mSignUp) {
        this.mSignUp = mSignUp;
    }

    public JMenuItem getMiRegisterAdministrator() {
        return miRegisterAdministrator;
    }

    public void setMiRegisterAdministrator(JMenuItem miRegisterAdministrator) {
        this.miRegisterAdministrator = miRegisterAdministrator;
    }

    public JMenuItem getMiRegisterBuyer() {
        return miRegisterBuyer;
    }

    public void setMiRegisterBuyer(JMenuItem miRegisterBuyer) {
        this.miRegisterBuyer = miRegisterBuyer;
    }

    public JMenuItem getMiRegisterCustomer() {
        return miRegisterCustomer;
    }

    public void setMiRegisterCustomer(JMenuItem miRegisterCustomer) {
        this.miRegisterCustomer = miRegisterCustomer;
    }

    public JMenuItem getMiRegisterMechanic() {
        return miRegisterMechanic;
    }

    public void setMiRegisterMechanic(JMenuItem miRegisterMechanic) {
        this.miRegisterMechanic = miRegisterMechanic;
    }

    public JMenuItem getMiRegisterSeller() {
        return miRegisterSeller;
    }

    public void setMiRegisterSeller(JMenuItem miRegisterSeller) {
        this.miRegisterSeller = miRegisterSeller;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton bSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private JMenu mSignUp;
    private JMenuItem miRegisterAdministrator;
    private JMenuItem miRegisterBuyer;
    private JMenuItem miRegisterCustomer;
    private JMenuItem miRegisterMechanic;
    private JMenuItem miRegisterSeller;
    // End of variables declaration//GEN-END:variables
}
